language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
        
install:
    - pip install -U platformio
    - pio update
    - pio lib install -g/--global
    #- python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci Game_Stable/Shoulder-Dev32/src --board=esp32dev
    - platformio ci Game_Stable/Watch_Mega/src --board=megaatmega2560 
    
notifications:
  email:
    on_success: change
    on_failure: change
