build: off
environment:

  matrix:
    - TOXENV: "py27"

# blocklist
branches:
  except:
  - Case
  - Old_Version
  - Beta
  - master

# safelist
branches:
  only: 
  - Stable

install:
  - cmd: pip install -U platformio
  - cmd: platformio lib -g install 4 13 135 419

#test_script:
#  - cmd: tox
    #Stable
#    - platformio ci --lib="." --board=esp32dev Game/One_Player/Device/Shoulder-Dev32/src
#    - platformio ci --lib="." --board=megaatmega2560 Game/One_Player/Device/Watch_Mega/src
#    - platformio ci --lib="." --board=megaatmega2560 Game/One_Player/Device/Server/src
    
    #Beta
    #- platformio ci --lib="." --board=megaatmega2560 Game_NBeta/Device/Server/src
    #- platformio ci --lib="." --board=esp32dev Game_NBeta/Device/Shoulder-Dev32/src
    #- platformio ci --lib="." --board=megaatmega2560 Game_NBeta/Device/Watch_Mega/src

